2020-10-06 14:19:39,670 ERROR: Exception on /user/sunni [GET] [in /Users/senayberhe/.local/share/virtualenvs/blog-CUSuk64f/lib/python3.8/site-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/Users/senayberhe/.local/share/virtualenvs/blog-CUSuk64f/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/senayberhe/.local/share/virtualenvs/blog-CUSuk64f/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/senayberhe/.local/share/virtualenvs/blog-CUSuk64f/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/senayberhe/.local/share/virtualenvs/blog-CUSuk64f/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/senayberhe/.local/share/virtualenvs/blog-CUSuk64f/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/senayberhe/.local/share/virtualenvs/blog-CUSuk64f/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/senayberhe/.local/share/virtualenvs/blog-CUSuk64f/lib/python3.8/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/senayberhe/Desktop/project/blog/app/main/routes.py", line 76, in user
    return render_template('user.html', user=user, posts=posts.items,
  File "/Users/senayberhe/.local/share/virtualenvs/blog-CUSuk64f/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/senayberhe/.local/share/virtualenvs/blog-CUSuk64f/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/senayberhe/.local/share/virtualenvs/blog-CUSuk64f/lib/python3.8/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/senayberhe/.local/share/virtualenvs/blog-CUSuk64f/lib/python3.8/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/senayberhe/.local/share/virtualenvs/blog-CUSuk64f/lib/python3.8/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/senayberhe/.local/share/virtualenvs/blog-CUSuk64f/lib/python3.8/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/senayberhe/Desktop/project/blog/app/templates/user.html", line 1, in <module>
    {% extends "base.html" %}
  File "/Users/senayberhe/.local/share/virtualenvs/blog-CUSuk64f/lib/python3.8/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/Users/senayberhe/Desktop/project/blog/app/templates/user.html", line 14, in root
    {% if user == current_user %}
  File "/Users/senayberhe/Desktop/project/blog/app/templates/base.html", line 14, in root
    <span class="icon-bar"></span>
  File "/Users/senayberhe/.local/share/virtualenvs/blog-CUSuk64f/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 10, in root
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  File "/Users/senayberhe/.local/share/virtualenvs/blog-CUSuk64f/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block_doc
    {% block body -%}
  File "/Users/senayberhe/.local/share/virtualenvs/blog-CUSuk64f/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 39, in block_html
  File "/Users/senayberhe/.local/share/virtualenvs/blog-CUSuk64f/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 92, in block_body
  File "/Users/senayberhe/Desktop/project/blog/app/templates/base.html", line 109, in block_content
    }, 1000);
  File "/Users/senayberhe/Desktop/project/blog/app/templates/user.html", line 59, in block_app_content
  File "/Users/senayberhe/.local/share/virtualenvs/blog-CUSuk64f/lib/python3.8/site-packages/jinja2/runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "/Users/senayberhe/.local/share/virtualenvs/blog-CUSuk64f/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/senayberhe/.local/share/virtualenvs/blog-CUSuk64f/lib/python3.8/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/senayberhe/.local/share/virtualenvs/blog-CUSuk64f/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/senayberhe/.local/share/virtualenvs/blog-CUSuk64f/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/Users/senayberhe/.local/share/virtualenvs/blog-CUSuk64f/lib/python3.8/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.export_posts'. Did you mean 'main.explore' instead?
2020-10-06 14:29:55,612 INFO: Microblog startup [in /Users/senayberhe/Desktop/project/blog/app/__init__.py:89]
